import type { Metadata } from "next";
import Image from "next/image";
import { Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { DockWrapper } from "@/components/dock-wrapper";
import { TooltipProvider } from "@/components/ui/tooltip";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", roboto.className)}>
      <body className="relative min-h-full flex flex-col px-4 overflow-hidden">
        <TooltipProvider>
          <Image
            src="/mac_tahoe_wallpaper.jpg"
            alt="Lock Screen"
            fill
            className="object-cover"
            priority
          />
          {children}
          <DockWrapper />
        </TooltipProvider>
      </body>
    </html>
  );
}
